---
#DESCRIPTION
#   Backup AWX/Tower using tower-cli

#NOTES 
#   File Name  : awx_tower_backup.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 4

#USAGE
#   ansible-playbook playbooks/awx_tower_backup -i inventory/servers
#   
#CHANGELOG
#   v1 03/09/2019   Playbook creation
#   v2 
#   




- hosts: all
  gather_facts: no
  serial: 1
  vars:
    backup_folder: /etc/ansible/awx-backup

  tasks:
    - name: Create root directory if don't exist
      file:
        path: "{{ backup_folder }}"
        state: directory
        mode: 0755  
      
    - name: Register timestamp variable
      local_action: command date +%Y%m%d-%H_%M
      register: timestamp  

    - debug:
          var: timestamp.stdout

    - name: Backup AWX/Tower using tower-cli
      shell: "tower-cli receive --tower-host http://{{ item }} --all >  {{ backup_folder }}/{{ timestamp.stdout }}_{{ item }}.json"
      with_items:
         - 192.168.0.19
         - 192.168.0.151
         - 192.168.0.152

         