---

#DESCRIPTION
#   This playbook check current available version of AWX on oficial repository
#   https://github.com/ansible/awx/releases

#NOTES 
#   File Name  : check_awx_available_version.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   
#   
#CHANGELOG
#   v1 15/01/2020  	Playbook creation
#  

- hosts: "{{ servers }}"
  gather_facts: no
  connection: local
  tasks:
    - name: Check current available version of AWX on oficial repository
      shell: "curl -s https://api.github.com/repos/ansible/awx/tags |egrep name |head -1 |awk '{print $2}' |tr -d ','"
      register: awx_version_available
      delegate_to: localhost

    - name: Check installed AWX Version
      command: "echo hola"
      register: awx_version_installed
      args:
        chdir: /etc/ansible

    - name: Backup AWX/Tower using tower-cli
      shell: "tower-cli receive --tower-host http://localhost --all >  /tmp/backup.json"
      register: output
      ignore_errors: yes    

    - name: Register variables to use into Tower workflow
      set_stats:
        data:
          telegram_msg: |
                    Check AWX version on {{ inventory_hostname }}
                    Version installed: {{ awx_version_installed.stdout }}
                    Version available: {{ awx_version_available.stdout }}

