---

#DESCRIPCIÓN
#   Este playbook arranca/apaga un servidor Lenovo via XCC

#NOTAS 
#   Nombre del fichero  : generic_lenovo_xcc_powerstate.yml
#   Autor     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Versión    : 1

#USO
#   
#   

#DOCUMENTACIÓN
#hhttps://docs.ansible.com/ansible/latest/collections/community/general/xcc_redfish_command_module.html
#https://pubs.lenovo.com/xcc-restapi/server_reset_operations_post#request-url

#CHANGELOG
#   v1 23/08/2024  	Creación del playbook
#   v2 


- hosts: all
  gather_facts: false
  serial: 1
  tasks:
  - name: Arranca servidor Lenovo
    community.general.xcc_redfish_command:
      category: Raw
      command: PostResource
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      resource_uri: "/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
      request_body:
         ResetType: "{{ state }}"  # ForceOn ForceOff    