---

#DESCRIPTION
#   This playbook sent telegram message to @miquelMariano, please change token and chat ID

#NOTES 
#   File Name  : telegram.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   
#   
#CHANGELOG
#   v1 20/04/2017  	Playbook creation
#   v2 16/08/2019  	Add notes 
#   v3 04/09/2019	  Add var default message to telegram_msg
#   v4 11/09/2019   Add quote on chat_id var

- hosts: all
  gather_facts: no
  connection: local
  vars:
    telegram_msg: "Hello world from Ansible"
  tasks:

    - name: Send notify to Telegram
      community.general.telegram:
       token: '304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8'
       api_args:
         chat_id: 6343788
         parse_mode: "markdown"
         text: "Your precious application has been deployed: https://example.com"
         disable_web_page_preview: true
         disable_notification: true

