---

- hosts: "{{ servers }}"
  gather_facts: false
  serial: 1
  tasks:
    - name: Sleep for 2 minutes and continue with play
      wait_for:
        timeout: 120
      delegate_to: localhost 
      

       
