---
#DESCRIPTION
#   Install Ansible AWX

#NOTES 
#   File Name  : linux_awx_install.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   
#
#   
#

#CHANGELOG
#   v1 19/11/2019   Playbook creation
#    


- hosts: "{{ servers }}"
  gather_facts: no
  tasks:

    - name: Install EPEL repo
      yum:
        name: epel-release
        state: latest

    - name: Install required packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
           - git
           - gcc
           - gcc-c++
           - nodejs
           - gettext
           - device-mapper-persistent-data
           - lvm2
           - bzip2
           - python-pip
           - yum-utils
           - ansible

#    - name: Add docker-ce repository
#      yum_repository:
#        name: docker-ce
#        description: docker-ce repository
#        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Add docker-ce repository
      shell: "yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"      

    - name: Install Docker CE
      yum:
        name: docker-ce
        state: latest  

    - name: Enable Docker CE service
      systemd:
        state: started
        name: docker
        enabled: yes
        masked: no  

    - name: Install Docker docker-compose
      pip:
        name: docker-compose   



  


    

#    - name: Make sure a service is enabled and running
#      systemd:
#        state: started
#        name: docker
#        enabled: yes
#        masked: no

#    - name: Update Python pip
#      pip:
#        name:
#          - pip
#        extra_args: --upgrade

#    - name: Install Python library dependencies
#      pip:
#        name:
#          - ansible
#          - docker-compose
#        extra_args: --upgrade




 