---
#DESCRIPTION
#   Install Ansible AWX

#NOTES 
#   File Name  : linux_awx_install.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   
#
#   
#

#CHANGELOG
#   v1 19/11/2019   Playbook creation
#    


- hosts: "{{ servers }}"
  gather_facts: no
  tasks:

    - name: Add docker-ce repository
      shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  
#    - name: Add docker-ce repository
#      yum_repository:
#        name: docker-ce
#        description: docker-ce repository
#        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install required packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
           - epel-release
           - jq 
           - yum-utils
           - device-mapper-persistent-data
           - lvm2
           - docker-ce
           - docker-compose
           - python2-pip

    - name: Make sure a service is enabled and running
      systemd:
        state: started
        name: docker
        enabled: yes
        masked: no

    - name: Install Python library dependencies
      pip:
        name:
          - pip
          - ansible
          - docker-compose
        extra_args: --upgrade



 