---
#DESCRIPTION
#   Install Ansible AWX

#NOTES 
#   File Name  : linux_awx_install.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 2

#USAGE
#   
#
#   
#

#CHANGELOG
#   v1 19/11/2019   Playbook creation
#   v2 16/01/2020   Update process


- hosts: "{{ servers }}"
  gather_facts: no
  tasks:

    - name: Install EPEL repo
      yum:
        name: epel-release
        state: latest

    - name: Install required packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
           - git
           - gcc
           - gcc-c++
           - nodejs
           - gettext
           - device-mapper-persistent-data
           - lvm2
           - bzip2
           - python-pip
           - yum-utils
           - ansible
           - python3
           - libselinux-python3 
           - python36-docker

    - name: Add docker-ce repository
      shell: "yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"      

    - name: Install Docker CE
      yum:
        name: docker-ce
        state: latest  

    - name: Enable Docker CE service
      systemd:
        state: started
        name: docker
        enabled: yes
        masked: no  

    - name: Install Docker docker-compose
      pip:
        name: docker-compose==1.23.2
        executable: pip-3.3

    - name: Download AWX packages version {{ version }}
      get_url:
        url: "https://github.com/ansible/awx/archive/{{ version }}.tar.gz"
        dest: /tmp/
        mode: '0755' 

    - name: Extract AWX installer
      shell: "tar xvfz awx-{{ version }}.tar.gz"
      args:
        chdir: /tmp/ 

#    - name: Extract AWX installer
#      unarchive: 
#        src: "/tmp/awx-{{ version }}.tar.gz"
#        dest: "/tmp/{{ version }}"

    - name: Remove AWX pachages compressed
      file:
        path: "/tmp/awx-{{ version }}.tar.gz"
        state: absent    

    - name: Install AWX
      shell: "ansible-playbook -i inventory install.yml"
      args:
          chdir: /tmp/awx-{{ version }}/installer

    - name: Configure firewall
      firewalld:
        service: https
        permanent: yes
        state: enabled