---
#DESCRIPTION
#   Install Ansible AWX

#NOTES 
#   File Name  : linux_awx_install.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   
#
#   
#

#CHANGELOG
#   v1 19/11/2019   Playbook creation
#    


- hosts: "{{ servers }}"
  gather_facts: no
  tasks:

    - name: Add docker-ce repository
      yum_repository:
        name: docker-ce.repo
        description: docker-ce repository
      baseurl: https://download.docker.com/linux/centos/

    - name: Install required packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
           - epel-release
           - jq 
           - yum-utils
           - device-mapper-persistent-data
           - lvm2
           - docker-ce
 