---

- hosts: all
  gather_facts: no
  tasks:

    - assert:
            that:
              - devices == inventory_hostname

    - name: Send telegram notification
      telegram:
         token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
         chat_id: 6343788
         msg: Check hosts > {{ inventory_hostname }} 
      ignore_errors: yes
      delegate_to: localhost
    
    - name: Ping
      ping:
      register: ping
  
    - debug:
         var: ping
  
    - name: Send telegram notification
      telegram:
         token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
         chat_id: 6343788
         msg: Ping OK > {{ inventory_hostname }} 
      ignore_errors: yes
      delegate_to: localhost
      when:
          - ping.ping == "pong"

     -name: Send telegram notification
      telegram:
         token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
         chat_id: 6343788
         msg: Ping NOK > {{ (inventory_hostname | difference(devices)) | first }}
      ignore_errors: yes
      delegate_to: localhost
 