---

- hosts: all
  gather_facts: no
  ignore_errors: yes
  serial: 1 
  tasks:
    
    - name: Ping
      ping:
      ignore_errors: yes
      register: ping
    
    - name: Hostname
      command: hostname
      register: hostname
      ignore_errors: yes

    - debug:
         var: ping  
    
    - debug:
         var: hostname.stdout

    - name: Send telegram updates
      telegram:
         token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
         chat_id: 6343788
         msg: OK > {{ hostname.stdout }} 
      ignore_errors: yes
      delegate_to: localhost
      when:
          - ping.ping == pong 
