---
#DESCRIPTION
#   Ping and send telegram notification

#NOTES 
#   File Name  : ping.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   
#
#   
#

#CHANGELOG
#   v1 03/09/2019   Playbook creation
#    


- hosts: all
  gather_facts: no
  tasks:

    - assert:
            that:
              - ansible_play_hosts == ansible_play_hosts_all
    
    - name: Pinging hosts
      ping:
      register: ping
      ignore_errors: yes
  
    - name: Send telegram notification SUCCESS hosts
      telegram:
         token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
         chat_id: '6343788'
         msg: Ping SUCCESS > {{ ansible_play_hosts }}|str
      ignore_errors: yes
      delegate_to: localhost
      run_once: true
      when:
          - ping.ping == "pong"

    - name: Send telegram notification FAILED hosts
      telegram:
         token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
         chat_id: '6343788'
         msg: Ping FAILED > {{ (ansible_play_hosts_all | difference(ansible_play_hosts)) }}
      delegate_to: localhost
      run_once: true
      when:
          - ansible_play_hosts is not defined
 