---

- hosts: all
  gather_facts: no
  tasks:

    - assert:
            that:
              - ansible_play_hosts == ansible_play_hosts_all
    
    - name: Ping
      ping:
      register: ping
  
    - debug:
         var: ansible_play_hosts_all
  
    - name: Send telegram notification
      telegram:
         token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
         chat_id: 6343788
         msg: Ping OK list > {{ ansible_play_hosts }} 
      ignore_errors: yes
      delegate_to: localhost
      run_once: true
      when:
          - ping.ping == "pong"

    - name: Send telegram notification
      telegram:
         token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
         chat_id: 6343788
         msg: Ping NOK list > {{ (ansible_play_hosts_all | difference(ansible_play_hosts)) }}
      delegate_to: localhost
      run_once: true
 