---

#DESCRIPTION
#   This playbook sent telegram message to @miquelMariano, please change token and chat ID

#NOTES 
#   File Name  : telegram.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   
#   
#CHANGELOG
#   v1 20/04/2017  Playbook creation
#   v2 16/08/2019  Add notes 
#  

- hosts: localhost
  connection: local
  tasks:
    - name: Send telegram message
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: 6343788
        msg: "{{ telegram_msg }}"

