---

- hosts: localhost
  connection: local
  tasks:
    - name: Send telegram message
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: 6343788
        msg: "{{ telegram_msg }}"

