---

#DESCRIPCIÓN
#   Este playbook gestiona el apagado o reinicio de un host ESXi

#NOTAS 
#   Nombre del fichero  : vmware_esxi_maintenance_mode.yml
#   Autor     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Versión    : 2

#USO
#   
#   

#DOCUMENTACIÓN
#https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_maintenancemode_module.html

#CHANGELOG
#   v1 23/08/2024 	Creación del playbook

- hosts: all
  gather_facts: false
  serial: 1
  tasks:
  - name: Apagar servidor ESXi
    community.vmware.vmware_host_powerstate:
       hostname: "{{ vc_hostname }}" 
       username: "{{ vc_username }}" 
       password: "{{ vc_password }}" 
       validate_certs: no
       esxi_hostname: "{{ esxi_hostname }}"
       state: shutdown-host
    delegate_to: localhost

