---

#DESCRIPCIÓN
#   Este playbook gestiona el apagado o reinicio de una VM

#NOTAS 
#   Nombre del fichero  : vmware_vm_powerstate.yml
#   Autor     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Versión    : 1

#USO
#   
#   

#DOCUMENTACIÓN
#https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_powerstate_module.html

#CHANGELOG
#   v1 27/08/2024 	Creación del playbook

- hosts: all
  gather_facts: false
  serial: 1
  tasks:
  - name: Apagar servidor ESXi
    community.vmware.vmware_guest_powerstate:
       hostname: "{{ vc_hostname }}" 
       username: "{{ vc_username }}" 
       password: "{{ vc_password }}" 
       folder: "{{ vm_folder }}"
       state: "{{ vm_powerstate }}"
       validate_certs: no
    delegate_to: localhost

