---

#DESCRIPCIÓN
#   Este playbook gestiona el modo mantenimiento en un host ESXi

#NOTAS 
#   Nombre del fichero  : vmware_esxi_maintenance_mode.yml
#   Autor     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Versión    : 2

#USO
#   
#   
#CHANGELOG
#   v1 13/11/2019  	Creación del playbook
#   v2 23/08/2024   Actualización parámetros


- hosts: all
  gather_facts: false
  serial: 1
  tasks:
  - name: Place a ESXi into Maintenance Mode
    community.vmware.vmware_maintenancemode:
       hostname: "{{ vc_hostname }}" 
       username: "{{ vc_username }}" 
       password: "{{ vc_password }}" 
       validate_certs: no
       esxi_hostname: "{{ esxi_hostname }}"
       vsan: noAction
       evacuate: true
       timeout: 3600
       state: "{{ maintenance_mode_status }}" # present o absent
    delegate_to: localhost

