---
#DESCRIPTION
#   Check or install windows updates and notify by telegram chat

#NOTES 
#   File Name  : win_updates.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 4

#USAGE
#   ansible-playbook playbooks/win_update.yml -i inventory/servers -e "servers=dc install_updates=false"
#   
#CHANGELOG
#   v1 19/05/2019   Playbook creation
#   v2 20/08/2019   Adapt to Tower/AWX
#   v3 22/08/2019   Change usage method  
#   v4 22/08/2019   Add before and after telegram notifications


- hosts: "{{ servers }}"
  serial: 1
  tasks:
    - name: Search windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - Windows Server 2016
          - Drivers
          - Definition Updates
          - Windows Defender
        state: searched
      register: list_of_found_updates

    - debug:
        var: list_of_found_updates

    - name: Send telegram updates
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: 6343788
        msg: Host {{ inventory_hostname }} >> {{ list_of_found_updates.found_update_count }} found updates before install.
      ignore_errors: yes
      delegate_to: localhost

    - name: Install all windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - Windows Server 2016
          - Drivers
          - Definition Updates
          - Windows Defender
        reboot: yes
      when:
          - install_updates|bool == true and list_of_found_updates.found_update_count|int != 0

    - name: Search windows updates after install
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - Windows Server 2016
          - Drivers
          - Definition Updates
          - Windows Defender
        state: searched
      register: list_of_found_updates  
      when:
          - install_updates|bool == true and list_of_found_updates.found_update_count|int != 0    

    - name: Send telegram updates after install
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: 6343788
        msg: Host {{ inventory_hostname }} >> {{ list_of_found_updates.found_update_count }} found updates after install.
      ignore_errors: yes
      delegate_to: localhost
      when:
          - install_updates|bool == true and list_of_found_updates.found_update_count|int != 0
