---
#DESCRIPTION
#   Manage Windows DNS

#NOTES 
#   File Name  : win_dns_record.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   ansible-playbook playbooks/win_dns_record.yml -i inventory/servers
# 
#VARIABLES
#servers: dc01.lab.local
#dns_zone: lab.local
#records:
#  - { type: A, state: present, name: prueba-awx, value: 10.0.0.1}
#
#CHANGELOG
#   v1 13/04/2020  Playbook creation
#   
#  

- hosts: "{{ servers }}"
  serial: 1
  tasks:

   - name: Add DNS static record
     win_dns_record:
       name: "{{ item.name }}"
       type: "{{ item.type }}"
       state: "{{ item.state }}"
       value: "{{ item.value }}"
       zone: "{{ dns_zone }}"
     when:
          - item.state == "present"
     with_items:
          - "{{ records }}"
       

   - name: Delete DNS static record
     win_dns_record:
       name: "{{ item.name }}"
       type: "{{ item.type }}"
       state: "{{ item.state }}"
       zone: "{{ dns_zone }}"
     when:
          - item.state == "absent"
     with_items:
          - "{{ records }}" 
                


            
