---
#DESCRIPTION
#   Manage Windows DNS

#NOTES 
#   File Name  : win_dns_record.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   ansible-playbook playbooks/win_dns_record.yml -i inventory/servers
#   
#CHANGELOG
#   v1 13/04/2020  Playbook creation
#   
#  

- hosts: "{{ servers }}"
  serial: 1
  tasks:

   - name: Add static record
     win_dns_record:
       name: "db1"
       type: "A"
       state: present
       zone: "{{ dns_zone }}"
     with_items:
          - "{{ records }}"
            
