---

- hosts: "{{ servers }}"
  gather_facts: no
  tasks:
    - name: Windows ping
      win_ping:
      register: task_output

    - name: Register variables to use into Tower workflow with send mail task
      set_stats:
        data:
          body_msg: "{{ task_output }}" 