---
#DESCRIPTION
#   Check or install windows updates and notify by telegram chat

#NOTES 
#   File Name  : win_updates.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 7

#USAGE
#   ansible-playbook playbooks/win_update.yml -i inventory/servers -e "servers=dc install_updates=false"
#   
#CHANGELOG
#   v1 19/05/2019   Playbook creation
#   v2 20/08/2019   Adapt to Tower/AWX
#   v3 22/08/2019   Change usage method  
#   v4 22/08/2019   Add before and after telegram notifications
#   v5 10/09/2019   Remove notification after updates installed
#   v6 11/09/2019   Add quote on chat_id var
#   v7 04/01/2020   Separate telegram message in multiple lines
#   v7 21/02/2020   Comment Definition Updates & Windows Defender

- hosts: "{{ servers }}"
  serial: 1
  tasks:
    - name: Search windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - Windows Server 2016
          - Drivers
#          - Definition Updates
#          - Windows Defender
          - Unclassified
        state: searched
      register: list_of_found_updates

    - name: Reboot server > {{ inventory_hostname }}
      win_reboot:
         reboot_timeout: 3600
      when:
          - list_of_found_updates.reboot_required|bool == true  

    - debug:
        var: list_of_found_updates

    - name: Send telegram updates
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: '6343788'
        msg: | 
           ========== WINDOWS UPDATE ==========
           Server >>>>>>>>>>> {{ inventory_hostname }}
           Found Updates >>>> {{ list_of_found_updates.found_update_count }} 
           Updates >>>>>>>>>> {{ list_of_found_updates.updates }} 
           Reboot required >> {{ list_of_found_updates.reboot_required }}
      delegate_to: localhost

    - name: Install all windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - Windows Server 2016
          - Drivers
#          - Definition Updates
#          - Windows Defender
          - Unclassified
        reboot: yes 
      when:
          - install_updates|bool == true and list_of_found_updates.found_update_count|int != 0
