---
#DESCRIPTION
#   Reboot windows servers

#NOTES 
#   File Name  : win_reboot.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   ansible-playbook playbooks/win_reboot.yml -i inventory/servers -e "servers=horizon confirm_reboot=true"
#   
#CHANGELOG
#   v1 19/05/2019  Playbook creation
#   
#  

- hosts: "{{ servers }}"
  serial: 1
  tasks:

    - name: Start play. Send telegram notification
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: 6343788
        msg:  Start task at {{ ansible_date_time.date }}  {{ ansible_date_time.time }}
      ignore_errors: yes
      delegate_to: localhost

    - name: Check system uptime > '{{ inventory_hostname }}' before reboot
      win_shell: 'Get-CimInstance -ClassName win32_operatingsystem | select lastbootuptime | ft -HideTableHeaders'
      register: uptime

    - debug:
        var: uptime

    - name: Send telegram uptime info before reboot
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: 6343788
        msg: '{{ inventory_hostname }} boot uptime before reboot: {{ uptime.stdout_lines[1] }}'
      ignore_errors: yes
      delegate_to: localhost

    - name: Reboot server > '{{ inventory_hostname }}'
      win_reboot:
         shutdown_timeout: 3600
         reboot_timeout: 3600
      when:
          - confirm_reboot|bool == true

    - name: Check system uptime > '{{ inventory_hostname }}' after reboot
      win_shell: 'Get-CimInstance -ClassName win32_operatingsystem | select lastbootuptime | ft -HideTableHeaders'
      register: uptime

    - name: Send telegram uptime info after reboot
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: 6343788
        msg: '{{ inventory_hostname }} boot uptime after reboot: {{ uptime.stdout_lines[1] }}'
      ignore_errors: yes
      delegate_to: localhost
      when:
          - confirm_reboot|bool == true
