---
#DESCRIPTION
#   Check or install windows updates and notify by telegram chat

#NOTES 
#   File Name  : win_updates.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   ansible-playbook playbooks/win_update.yml -i inventory/servers -e "servers=dc install_updates=false"
#   
#CHANGELOG
#   v1 19/05/2019   Playbook creation
#   v2 20/08/2019   Adapt to Tower/AWX
#   v3 22/08/2019   Change usage method  


- hosts: "{{ servers }}"
  serial: 1
  tasks:
    - name: Search-only, return list of found updates (if any).
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - Windows Server 2016
          - Drivers
          - Definition Updates
          - Windows Defender
        state: searched
      register: list_of_found_updates

    - debug:
        var: list_of_found_updates

    - name: Send telegram notification
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: 6343788
        msg: Host {{ inventory_hostname }} >> {{ list_of_found_updates.found_update_count }} found updates.
      ignore_errors: yes

    - name: Install all security, critical, and rollup updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
          - Windows Server 2016
          - Drivers
          - Definition Updates
          - Windows Defender
        reboot: yes
      when:
          - install_updates|bool == true

#    - debug:
#        var: groups[ "{{ servers }}" ]

#- hosts: localhost
#  connection: local
#  tasks:
#    - name: Send telegram notification
#      telegram:
#        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
#        chat_id: 6343788
#        msg: Host {{ hostvars[item].inventory_hostname }} >> {{ hostvars[item].list_of_found_updates.found_update_count }} found updates.
#        msg: Host {{ hostvars[item].inventory_hostname }} >> {{ hostvars[item].list_of_found_updates }}
#      with_items:
#        -  "{{ groups[servers] }}"
#      ignore_errors: yes


# - hosts: "{{ servers }}"
#   tasks:
#     - name: Install all security, critical, and rollup updates
#       win_updates:
#         category_names:
#           - SecurityUpdates
#          - CriticalUpdates
#          - UpdateRollups
#          - Updates
#          - Windows Server 2016
#          - Drivers
#          - Definition Updates
#          - Windows Defender
#        reboot: yes
#      when:
#          - install_updates|bool == true