---
#DESCRIPTION
#   Reboot windows servers

#NOTES 
#   File Name  : win_reboot.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   ansible-playbook playbooks/win_reboot.yml -i inventory/servers -e "servers=horizon confirm_reboot=true"
#   
#CHANGELOG
#   v1 19/05/2019  Playbook creation
#   
#  

- hosts: "{{ servers }}"
  serial: 1
  tasks:

    - name: Check system uptime > '{{ inventory_hostname }}' before reboot
      win_shell: 'Get-CimInstance -ClassName win32_operatingsystem | select lastbootuptime | ft -HideTableHeaders'
      register: uptime_before

    - name: Reboot server > '{{ inventory_hostname }}'
      win_reboot:
         reboot_timeout: 3600
      when:
          - confirm_reboot|bool == true

    - name: Check system uptime > '{{ inventory_hostname }}' after reboot
      win_shell: 'Get-CimInstance -ClassName win32_operatingsystem | select lastbootuptime | ft -HideTableHeaders'
      register: uptime_after

    - name: Send telegram uptime info after reboot
      telegram:
        token: 304017237:AAHpKXZBaw_wOF3H-ryhWl3F3wqIVP_Zqf8
        chat_id: '6343788'
        msg: | 
           ========== WINDOWS UPTIME INFO ==========
           Server >>>>>>>>>>> {{ inventory_hostname }}
           Boot time before reboot >>>> {{ uptime_before.stdout_lines[1] }}
           Boot time after reboot >>>> {{ uptime_after.stdout_lines[1] }}
      ignore_errors: yes
      delegate_to: localhost
      when:
          - confirm_reboot|bool == true
