---

- hosts: "{{ servers }}"
  gather_facts: no
  tasks:
    - name: Windows ping
      win_ping:
      register: task_output

    - name: Register variables to use into Tower workflow
      set_stats:
        data:
          output: "{{ task_output }}" 