---
#DESCRIPTION
#   Manage active directory computer accounts

#NOTES 
#   File Name  : win_domain_computer.yml
#   Author     : Miquel Mariano - @miquelMariano | https://miquelmariano.github.io
#   Version    : 1

#USAGE
#   ansible-playbook playbooks/win_domain_computer.yml -i inventory/servers 
#   
#CHANGELOG
#   v1 11/05/2020  Playbook creation
#   
#  

- hosts: vms
  gather_facts: false
  serial: 1
  tasks:
    - name: Demo
      win_domain_computer:
        name: "{{ inventory_hostname }}.{{ dc_domain }}"
#        dns_hostname: one_linux_server.my_org.local
        ou: "{{ domain_ou }}"
        description: Demo AWX
        enabled: yes
        state: present
      delegate_to: "{{ dc }}"
