---

- name: Ensure epel-release repo are installed
  yum:
    name: epel-release
    state: latest
  ignore_errors: yes  


- name: Ensure common software are installed
  yum:
    name: "{{ packages }}"
    state: present #latest
  vars:
    packages:
      - vim
      - git
      - htop
      - iotop
      - net-tools
      - mlocate
      - libselinux-python
      - ansible
      - ntp
      - python-pip
      - wget
      - npm #Required for install gtop
      - system-storage-manager
      - ntp
  when: ansible_os_family == 'RedHat'
  ignore_errors: yes

- name: Install "gtop" node.js package.
  npm:
    name: gtop 
    global: yes
  ignore_errors: yes  

- name: Update all system
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"
  notify:
    - RebootVM



